version: 2

sources:
  - name: aw
    schema: aw
    description:
    tables:     
      - name: sales_salesorderheader
        description: General sales order information.
      - name: sales_salesorderdetail
        description: Individual products associated with a specific sales order.
      - name: sales_creditcard
        description: Customer credit card information.
      - name: sales_salesreason
        description: Lookup table of customer purchase reasons.
      - name: sales_customer
        description: Current customer information.
      - name: person_address
        description: Street address information for customers, employees, and vendors.
      - name: person_stateprovince
        description: State and province lookup table.
      - name: person_countryregion
        description: Lookup table containing the ISO standard codes for countries and regions.
      - name: production_product
        description: Products sold or used in the manfacturing of sold products.
      - name: person_person
        description: Human beings involved with AdventureWorks such as employees, customer contacts, and vendor contacts.
      - name: sales_salesorderheadersalesreason
        description: Cross-reference table mapping sales orders to sales reason codes.
